# Add a menu link in admin/config page.
d8_admin_config_example.admin_config:
  title: 'Drupal 8 - Admin Config Example'
  description: 'Drupal 8 - Admin Config Example : Custom module development.'
  route_name: d8_admin_config_example.admin_config
  weight: -30
  parent: system.admin_config_development
